schema: xgc2.product.v1
id: xgc2-gazebo-sim-scout
name: XGC2 Gazebo Classic Scout
version: 0.4.9-37
kind: ros1-apt
summary: AgileX Scout Gazebo Classic simulation package for ROS Noetic.
ros:
  distro: noetic
  packages:
  - gazebo_sim_scout
apt:
  distribution: focal
  install:
  - ros-noetic-xgc2-gazebo-sim-scout
  packages:
  - ros-noetic-xgc2-gazebo-sim-scout
  package_architectures:
    ros-noetic-xgc2-gazebo-sim-scout:
    - amd64
    - arm64
  depends:
  - ros-noetic-scout-msgs (>= 0.3.3-5)
  - ros-noetic-urdf
  - ros-noetic-xacro
  - ros-noetic-xgc2-scout-description (>= 0.4.10-14)
  - ros-noetic-xgc2-gazebo-sim-worlds (>= 1.1.0-14)
  - ros-noetic-xgc2-gazebo-sim-vrpn-bridge (>= 1.1.0-13)
usage:
  install: 'sudo apt update

    sudo apt install ros-noetic-xgc2-gazebo-sim-scout

    '
  smoke_test: 'roslaunch --files gazebo_sim_scout simple.launch rviz:=false

    '
ownership:
  paths:
  - /opt/ros/noetic/share/gazebo_sim_scout
  - /opt/ros/noetic/lib/gazebo_sim_scout
  - /opt/ros/noetic/lib/libscout_gazebo.a
release:
  requires:
  - xgc2-scout-description
  dependency_policy:
    xgc2-gazebo-sim-vrpn-bridge: verify
    xgc2-gazebo-sim-scenes: verify
    xgc2-scout-description: verify
    xgc2-scout-msgs: rebuild
  apt_versions:
    focal: 0.4.9-37
