scout_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

scout_motor_fr_controller:
  type: scout_gazebo/WheelVelocityController
  p: 1.8
  i: 10.0
  joint: front_right_wheel

scout_motor_fl_controller:
  type: scout_gazebo/WheelVelocityController
  p: 1.8
  i: 10.0
  joint: front_left_wheel

scout_motor_rl_controller:
  type: scout_gazebo/WheelVelocityController
  p: 1.8
  i: 10.0
  joint: rear_left_wheel

scout_motor_rr_controller:
  type: scout_gazebo/WheelVelocityController
  p: 1.8
  i: 10.0
  joint: rear_right_wheel
